-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.asset_categories
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT asset_categories_pkey PRIMARY KEY (id),
    CONSTRAINT asset_categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.assets
(
    id serial NOT NULL,
    category_id integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    purchase_date date NOT NULL,
    purchase_cost numeric(12, 2) NOT NULL,
    current_value numeric(12, 2),
    depreciation_rate numeric(5, 2),
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    location character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT assets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_ledger
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default",
    invoice_id integer,
    invoice_no character varying(50) COLLATE pg_catalog."default",
    debit numeric(10, 2) DEFAULT 0,
    credit numeric(10, 2) DEFAULT 0,
    debt numeric(10, 2),
    note text COLLATE pg_catalog."default",
    transaction_type character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT customer_ledger_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employee_types
(
    id serial NOT NULL,
    type_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT employee_types_pkey PRIMARY KEY (id),
    CONSTRAINT employee_types_type_name_key UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    id serial NOT NULL,
    employee_type_id integer NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    "position" character varying(100) COLLATE pg_catalog."default",
    salary numeric(12, 2) NOT NULL,
    hire_date date NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'active'::character varying,
    department character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT employees_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.expense_categories
(
    id serial NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT expense_categories_pkey PRIMARY KEY (id),
    CONSTRAINT expense_categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.expenses
(
    id serial NOT NULL,
    category_id integer NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    amount numeric(12, 2) NOT NULL,
    date date NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.invoice_items
(
    id serial NOT NULL,
    invoice_id integer,
    description character varying(200) COLLATE pg_catalog."default",
    price numeric(10, 2),
    quantity integer DEFAULT 1,
    stock_id integer,
    product_name character varying(200) COLLATE pg_catalog."default",
    amount numeric(10, 2),
    CONSTRAINT invoice_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.invoices
(
    id serial NOT NULL,
    invoice_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    total_amount numeric(10, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'unpaid'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    invoice_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'invoice'::character varying,
    advance_paid numeric(10, 2) DEFAULT 0,
    customer_id integer,
    customer_name character varying(100) COLLATE pg_catalog."default",
    sale_id integer,
    outstanding_debt numeric(10, 2) DEFAULT 0,
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT invoices_invoice_no_key UNIQUE (invoice_no)
);

CREATE TABLE IF NOT EXISTS public.ledger
(
    id serial NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    invoice_id integer,
    invoice_no character varying(20) COLLATE pg_catalog."default",
    debit numeric(10, 2) DEFAULT 0,
    credit numeric(10, 2) DEFAULT 0,
    note text COLLATE pg_catalog."default",
    date timestamp without time zone DEFAULT now(),
    CONSTRAINT ledger_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_records
(
    id serial NOT NULL,
    customer_id integer NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default",
    sale_id integer,
    invoice_id integer,
    payment_amount numeric(10, 2) NOT NULL,
    payment_type character varying(50) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT payment_records_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.production_queue
(
    id serial NOT NULL,
    product_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    stock_id integer,
    required_quantity integer NOT NULL,
    notes text COLLATE pg_catalog."default",
    priority character varying(20) COLLATE pg_catalog."default" DEFAULT 'normal'::character varying,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    sale_id integer,
    created_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT production_queue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sale_items
(
    id serial NOT NULL,
    sale_id integer NOT NULL,
    stock_id integer,
    product_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    amount numeric(10, 2),
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT sale_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id serial NOT NULL,
    sale_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_id integer NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    total_amount numeric(10, 2) NOT NULL,
    advance_paid numeric(10, 2) DEFAULT 0,
    balance numeric(10, 2),
    payment_type character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT sales_pkey PRIMARY KEY (id),
    CONSTRAINT sales_sale_no_key UNIQUE (sale_no)
);

CREATE TABLE IF NOT EXISTS public.stock
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    quantity integer DEFAULT 0,
    category character varying(100) COLLATE pg_catalog."default",
    size character varying(50) COLLATE pg_catalog."default",
    extra text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    minimum_stock integer DEFAULT 10,
    CONSTRAINT stock_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.assets
    ADD CONSTRAINT assets_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.asset_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_assets_category_id
    ON public.assets(category_id);


ALTER TABLE IF EXISTS public.customer_ledger
    ADD CONSTRAINT customer_ledger_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.customer_ledger
    ADD CONSTRAINT customer_ledger_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_employee_type_id_fkey FOREIGN KEY (employee_type_id)
    REFERENCES public.employee_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_employees_type_id
    ON public.employees(employee_type_id);


ALTER TABLE IF EXISTS public.expenses
    ADD CONSTRAINT expenses_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.expense_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_expenses_category_id
    ON public.expenses(category_id);


ALTER TABLE IF EXISTS public.invoice_items
    ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.invoice_items
    ADD CONSTRAINT invoice_items_stock_id_fkey FOREIGN KEY (stock_id)
    REFERENCES public.stock (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoices
    ADD CONSTRAINT invoices_sale_id_fkey FOREIGN KEY (sale_id)
    REFERENCES public.sales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ledger
    ADD CONSTRAINT ledger_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.payment_records
    ADD CONSTRAINT payment_records_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payment_records
    ADD CONSTRAINT payment_records_invoice_id_fkey FOREIGN KEY (invoice_id)
    REFERENCES public.invoices (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment_records
    ADD CONSTRAINT payment_records_sale_id_fkey FOREIGN KEY (sale_id)
    REFERENCES public.sales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.production_queue
    ADD CONSTRAINT production_queue_sale_id_fkey FOREIGN KEY (sale_id)
    REFERENCES public.sales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.production_queue
    ADD CONSTRAINT production_queue_stock_id_fkey FOREIGN KEY (stock_id)
    REFERENCES public.stock (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sale_items
    ADD CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id)
    REFERENCES public.sales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sale_items
    ADD CONSTRAINT sale_items_stock_id_fkey FOREIGN KEY (stock_id)
    REFERENCES public.stock (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;